### ISSUE TITLE
Uncaught node.js Error 

### ISSUE THREAD

**Issue by escapologyBB** [andrew/Nodecopter.app#1]
Hi,

I connected to the drone's Wi-Fi and then opened the app, I could see the UI and video feed updating successfully. However, when I pressed Takeoff the drone popped into the air properly but the app went a pale blue colour with a white fluffy cloud scudding across the page along with the following error message:

``` javascript
Uncaught node.js Error 

TypeError: Cannot call method 'log' of null
    at Client.eval (file:///Applications/Nodecopter.app/Contents/Resources/app.nw/app.js:87:11)
    at Client.EventEmitter.emit (events.js:92:17)
    at Client.eval (/Applications/Nodecopter.app/Contents/Resources/app.nw/node_modules/ar-drone/lib/Client.js:130:21)
    at Client._processNavdata (/Applications/Nodecopter.app/Contents/Resources/app.nw/node_modules/ar-drone/lib/Client.js:134:5)
    at Client._handleNavdata (/Applications/Nodecopter.app/Contents/Resources/app.nw/node_modules/ar-drone/lib/Client.js:121:8)
    at UdpNavdataStream.EventEmitter.emit (events.js:95:17)
    at UdpNavdataStream._handleMessage (/Applications/Nodecopter.app/Contents/Resources/app.nw/node_modules/ar-drone/lib/navdata/UdpNavdataStream.js:73:10)
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:437:8)
```

All the while the drone continued hovering, I restarted the app at which point the drone landed safely and I was able to recreate this behaviour three or four times.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
